fix: Added second example to APIs tagged with property
rdkcentral/firebolt-core-sdk pull request #109
Opened 2023-04-07 15:47 UTC by kevinshahfws

2023-04-10 16:51 UTC, jlacivita approved these changes

2023-04-13 13:51 UTC, jlacivita requested changes

2023-04-13 14:24 UTC, kevinshahfws commented on src/sdks/manage/sdk.config.json
>                  "xrn:firebolt:capability:token:session",
addressed

2023-04-13 14:41 UTC, kpears201 approved these changes

2023-04-13 19:38 UTC, merged

2023-04-17 16:28 UTC, kevinshahfws commented
:tada: This PR is included in version 0.11.0-one-repository.1 :tada:

The release is available on:
- [npm package (@test dist-tag)](https://www.npmjs.com/package/@firebolt-js/sdks/v/0.11.0-one-repository.1)
- [GitHub release](https://github.com/rdkcentral/firebolt-core-sdk/releases/tag/v0.11.0-one-repository.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-17 18:58 UTC, kevinshahfws commented
:tada: This PR is included in version 0.11.0-next.1 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-core-sdk/releases/tag/v0.11.0-next.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-01 20:54 UTC, kevinshahfws commented
:tada: This PR is included in version 0.11.0 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-core-sdk/releases/tag/v0.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: